Bot:
  Token: 'MTI3Mzc1NTUyNjg5NDcxODk3Ng.GoYuIF.NUtcPxR1khAhOuLBR9Hh_u6GciuLvo8iPZRMio'
  Guilds:
    Global: '1256007732528676885'
    Factions: '1277682664131919882'
  Activity:
    Message: 'Atualmente estamos com %member_amount% membros!'

Config:
  JoinRole: ''
  Factions:
    Channel: ''
    Category: ''
    Message: 'ğŸ·ï¸ A FacÃ§Ã£o **%tag%** **%name%** confirmou presenÃ§a em nosso âš”ï¸ **FACTIONS**'
  Status:
    Channel: ''
    Active: 'Online'
    Style:
      Online: 'ğŸŸ¢ Online'
      Maintenance: 'ğŸŸ  ManutenÃ§Ã£o'
      Offline: 'ğŸ”´ Desligado'

Ticket:
  Logs: ''
  Channel: ''
  Category: ''
  StaffRole: ''
  Categories:
    Duvidas/Problemas: ''
    ConfirmarFacÃ§Ã£o: ''
    Parcerias: ''
    RevisÃµes: ''
    RelatarBugs: ''
    Reportar: ''
    Outros: ''